### ISSUE TITLE
Migration to Julia v0.6

### ISSUE THREAD

**Issue by dfornika** [WGS-TB/MentaLiST#13]
I saw this notice that Julia v0.5 is now officially unmaintained:

https://discourse.julialang.org/t/julia-0-5-is-now-officially-unmaintained/8169

It may be a good time to look at how easy it would be to migrate to v0.6

**Comment by pedrofeijao** [comment]
I did some tests to upgrade mentalist to 0.6, a while ago, and I was getting some errors. Then I found out why. Julia has a terrible loading time for heavy libraries, such as BioJulia and others, up to 15 seconds of startup time! It basically unacceptable, and it did not seem to get better on 0.6.
So, since the beginning of mentalist, I used a trick to load libraries, only loading them 'on-the- fly' for methods that really needed it, since it would be horrible for the user to wait for 15s just to run 'mentalist -h'. This was done by only importing the other '.jl' source files inside the functions that needed them. Ugly, but worked.
But, this trick does not work on 0.6, so I decided to keep it as it is. 
I would be great if we can find a way to load packages on demand on 0.6, otherwise it is just ridiculous to wait 15 seconds (did I say 15 SECONDS) to just start to run after loading packages.
Otherwise, trying to find a way to speed up package loading, but from my gogleeing it seems that everybody has this problem and nobody can fix it.

**Comment by dfornika** [comment]
One potential work-around might be to make `mentalist` a wrapper script in bash, python or that just handles showing the help options and launching the sub-commands, which would still be implemented in Julia.

**Comment by pedrofeijao** [comment]
The last commit in the master branch makes mentalist 0.6 compatible. Time to show help message is down to "only" 4.5 seconds.

**Comment by dfornika** [comment]
Ok, I'd like to merge `master` into the `mentalist_v0.2` branch, then I'll tag a `v0.2.1` release on the `mentalist_v0.2` branch.

**Comment by pedrofeijao** [comment]
That works for me.
